(() => {
'use strict';
const $ = id => document.getElementById(id);
const norm = v => String(v ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const fmt = v => new Intl.NumberFormat('es-CO',{maximumFractionDigits:2}).format(Number(v)||0);
const keyOf = (site,address='') => `${norm(site)}|${norm(address)}`;
const BASE = Array.isArray(window.SIMECO_REGISTROS) ? window.SIMECO_REGISTROS : [];
const SYNC = window.SIMECO_TERRITORIAL_SYNC || {};
const EXCEPTIONS = Array.isArray(window.SIMECO_SERVICE_EXCEPTIONS?.exceptions) ? window.SIMECO_SERVICE_EXCEPTIONS.exceptions : [];
const exceptionFor = (site,address,service='energyKwh') => EXCEPTIONS.find(ex=>ex.service===service && norm(ex.key||'')===norm(`${site}|${address||''}`)) || null;
const META_KEY='simeco2_clasificacion_sedes_energia_v3';
let manual={};
try{ manual=JSON.parse(localStorage.getItem(META_KEY)||'{}')||{}; }catch{ manual={}; }
const empty={zone:'Sin clasificar',territoryType:'Sin clasificar',commune:'Sin clasificar',neighborhood:'Sin clasificar',nucleus:'Sin clasificar',siteType:'Sin clasificar',source:'Factura',confidence:'Pendiente'};
const records=BASE.filter(r=>r&&r.site&&r.period).map(r=>{const hasEnergy=r.energyKwh!==null&&r.energyKwh!==undefined&&r.energyKwh!==''&&Number.isFinite(Number(r.energyKwh));const energyKwh=hasEnergy?Number(r.energyKwh):null;return {...r,hasEnergy,energyKwh,co2kg:hasEnergy?(Number.isFinite(Number(r.co2kg))?Number(r.co2kg):energyKwh*0.126):null,address:r.address||''};});
const siteMap=new Map();
for(const r of records){const k=keyOf(r.site,r.address);if(!siteMap.has(k))siteMap.set(k,{key:k,site:r.site,address:r.address,records:[]});siteMap.get(k).records.push(r);}
function meta(k){return {...empty,...(SYNC[k]||{}),...(manual[k]||{})};}
function priority(total,months,hasEnergy){if(!hasEnergy)return 'unmeasured';const avg=months?total/months:0;return avg>=5000?'high':avg>=2000?'medium':'low';}
function filters(){return {q:norm($('globalSiteSearch')?.value),zone:$('zoneFilter')?.value||'',territoryType:$('territoryTypeFilter')?.value||'',commune:$('communeFilter')?.value||'',neighborhood:$('neighborhoodFilter')?.value||'',nucleus:$('nucleusFilter')?.value||'',siteType:$('siteTypeFilter')?.value||'',siteKey:$('specificSiteFilter')?.value||'',period:$('globalPeriodFilter')?.value||'',service:$('globalServiceFilter')?.value||'',priority:$('priorityFilter')?.value||''};}
function siteRows(){return [...siteMap.values()].map(s=>{const m=meta(s.key);const recs=s.records;const energyRecs=recs.filter(r=>r.hasEnergy);const energy=energyRecs.reduce((a,r)=>a+(r.energyKwh||0),0);const periods=new Set(recs.map(r=>r.period)).size;const energyPeriods=new Set(energyRecs.map(r=>r.period)).size;const energyException=exceptionFor(s.site,s.address);return {...s,meta:m,energy,periods,energyPeriods,hasEnergy:energyRecs.length>0,energyException,priority:priority(energy,energyPeriods,energyRecs.length>0)};});}
function matchesSite(s,f,skip=''){
 const m=s.meta; const hay=norm([s.site,s.address,m.zone,m.territoryType,m.commune,m.neighborhood,m.nucleus,m.siteType].join(' '));
 if(skip!=='q'&&f.q&&!hay.includes(f.q))return false;
 for(const [field,val] of [['zone',f.zone],['territoryType',f.territoryType],['commune',f.commune],['neighborhood',f.neighborhood],['nucleus',f.nucleus],['siteType',f.siteType]]) if(skip!==field&&val&&norm(m[field])!==norm(val))return false;
 if(skip!=='siteKey'&&f.siteKey&&s.key!==f.siteKey)return false;
 if(skip!=='priority'&&f.priority&&s.priority!==f.priority)return false;
 return true;
}
function filteredRecords(){const f=filters();const siteByKey=new Map(siteRows().map(s=>[s.key,s]));const allowed=new Set([...siteByKey.values()].filter(s=>matchesSite(s,f)).map(s=>s.key));return records.filter(r=>{const sk=keyOf(r.site,r.address),site=siteByKey.get(sk);if(!allowed.has(sk))return false;if(f.period&&r.period!==f.period)return false;if(f.service==='energia'&&!r.hasEnergy&&!site?.energyException)return false;return true;});}
function aggregate(recs){const map=new Map();for(const r of recs){const k=keyOf(r.site,r.address);if(!map.has(k))map.set(k,{key:k,site:r.site,address:r.address,energy:0,co2:0,energyCount:0,periods:new Set()});const x=map.get(k);if(r.hasEnergy){x.energy+=r.energyKwh||0;x.co2+=r.co2kg||0;x.energyCount+=1;}x.periods.add(r.period);}return [...map.values()].map(x=>({...x,periodCount:x.periods.size,hasEnergy:x.energyCount>0,energyException:exceptionFor(x.site,x.address),meta:meta(x.key)})).sort((a,b)=>Number(b.hasEnergy)-Number(a.hasEnergy)||b.energy-a.energy||String(a.site).localeCompare(String(b.site),'es'));}
function values(rows,field){return [...new Set(rows.map(x=>x.meta[field]||'Sin clasificar'))].sort((a,b)=>a.localeCompare(b,'es',{numeric:true}));}
function fill(id,vals,first,current){const e=$(id);if(!e)return;e.innerHTML=`<option value="">${first}</option>`+vals.map(v=>`<option>${escapeHtml(v)}</option>`).join('');const o=[...e.options].find(o=>norm(o.value)===norm(current));if(o)e.value=o.value;}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function googleMapsUrl(address,schoolName=''){const raw=String(address||'').trim(),school=String(schoolName||'').replace(/\s+/g,' ').trim();if(!raw||/sin direcci[oó]n/i.test(raw))return '';const query=[school,raw,'Medellín','Antioquia','Colombia'].filter(Boolean).join(', ');return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;}
function mapAddressLink(address,label,schoolName=''){const raw=String(address||'').trim(),text=String(label||raw||'Sin dirección'),school=String(schoolName||'').trim(),url=googleMapsUrl(raw,school);return url?`<a class="map-address school-map-link" href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer" title="Abrir ubicación del colegio en Google Maps">🏫 ${escapeHtml(text)}</a>`:`<span class="map-address-unavailable">${escapeHtml(text)}</span>`;}
function refreshOptions(){const f=filters(),rows=siteRows();for(const [id,field,first] of [['zoneFilter','zone','Todas'],['territoryTypeFilter','territoryType','Todos'],['communeFilter','commune','Todas'],['neighborhoodFilter','neighborhood','Todos'],['nucleusFilter','nucleus','Todos'],['siteTypeFilter','siteType','Todos']])fill(id,values(rows.filter(s=>matchesSite(s,f,field)),field),first,f[field]);
 const matching=rows.filter(s=>matchesSite(s,f,'siteKey')).sort((a,b)=>a.site.localeCompare(b.site,'es'));const ss=$('specificSiteFilter');if(ss){ss.innerHTML='<option value="">Todas</option>'+matching.map(s=>`<option value="${escapeHtml(s.key)}">${escapeHtml(s.site)}</option>`).join('');if(matching.some(s=>s.key===f.siteKey))ss.value=f.siteKey;}
 fill('globalPeriodFilter',[...new Set(records.map(r=>r.period))].sort(),'Todos',f.period);
 const dl=$('siteSearchSuggestions');if(dl)dl.innerHTML=matching.slice(0,300).map(s=>`<option value="${escapeHtml(s.site)}"></option>`).join('');
}
function render(){const recs=filteredRecords();const rows=aggregate(recs);const measured=rows.filter(r=>r.hasEnergy),energy=measured.reduce((a,x)=>a+x.energy,0),co2=measured.reduce((a,x)=>a+x.co2,0),periods=new Set(recs.map(r=>r.period)).size;
 $('territorialSitesCount').textContent=fmt(rows.length);$('territorialPeriodsCount').textContent=fmt(periods);$('territorialEnergyTotal').textContent=measured.length?fmt(energy)+' kWh':'Sin lecturas';$('territorialCo2Total').textContent=measured.length?fmt(co2/1000)+' t CO₂e':'No calculable';
 $('territorialResultsBody').innerHTML=rows.slice(0,500).map((r,i)=>{const energyText=r.hasEnergy?`<strong>${fmt(r.energy)} kWh</strong>`:(r.energyException?'<span class="quality-badge external">Contrato separado</span>':'<span class="not-available">No identificada</span>');const co2Text=r.hasEnergy?`${fmt(r.co2/1000)} t`:(r.energyException?'Pendiente de integrar':'No calculable');return `<tr><td>${i+1}</td><td><strong>${escapeHtml(r.site)}</strong><small class="site-meta-line">${mapAddressLink(r.address,r.address||'Sin dirección',r.site)}</small></td><td>${escapeHtml(r.meta.zone)}</td><td>${escapeHtml(r.meta.commune)}</td><td>${escapeHtml(r.meta.nucleus)}</td><td>${fmt(r.periodCount)}</td><td>${energyText}</td><td>${co2Text}</td></tr>`;}).join('')||'<tr><td colspan="8">No hay datos para los filtros seleccionados.</td></tr>';
 const f=filters();const active=Object.entries(f).filter(([,v])=>v).map(([k])=>k);$('filterStatus').textContent=active.length?'Filtros activos: '+active.join(', ')+'.':'Filtros listos · mostrando todas las sedes con datos.';$('filterSummary').innerHTML=`Mostrando <strong>${fmt(rows.length)} sede(s)</strong> y <strong>${fmt(recs.length)} registro(s)</strong> obtenidos de las facturas de energía eléctrica.`;draw(rows.slice(0,20));
}
function draw(rows){const c=$('siteChart');if(!c)return;const dpr=Math.min(devicePixelRatio||1,2),w=1500,rowH=42,h=Math.max(420,100+rows.length*rowH);c.width=w*dpr;c.height=h*dpr;c.style.width=w+'px';c.style.height=h+'px';const x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);x.font='700 18px system-ui';x.fillStyle='#153b34';x.fillText('Ranking de sedes por consumo eléctrico total',24,35);x.font='600 12px system-ui';x.fillStyle='#607a74';x.fillText('Solo las sedes con kWh verificados reciben una posición medible',24,55);const max=Math.max(...rows.filter(r=>r.hasEnergy).map(r=>r.energy),1);rows.forEach((r,i)=>{const y=85+i*rowH;x.fillStyle='#173d36';x.font='600 12px system-ui';x.fillText((r.site||'').slice(0,34),20,y+14);x.fillStyle='#e8f5f1';x.fillRect(300,y,650,20);if(r.hasEnergy){x.fillStyle='#10ae88';x.fillRect(300,y,650*r.energy/max,20);}x.fillStyle='#173d36';x.fillText(r.hasEnergy?`${fmt(r.energy)} kWh · ${fmt(r.co2/1000)} t CO₂e`:(r.energyException?'Contrato separado · pendiente de integrar':'Energía no identificada'),970,y+14);});}
function renderClassification(){const body=$('classificationBody');if(!body)return;body.innerHTML=siteRows().map(s=>{const m=s.meta;return `<tr><td><strong>${escapeHtml(s.site)}</strong></td><td>${mapAddressLink(s.address,s.address||'Sin dirección',s.site)}</td><td><input data-k="${escapeHtml(s.key)}" data-f="zone" value="${escapeHtml(m.zone)}"></td><td><input data-k="${escapeHtml(s.key)}" data-f="territoryType" value="${escapeHtml(m.territoryType)}"></td><td><input data-k="${escapeHtml(s.key)}" data-f="commune" value="${escapeHtml(m.commune)}"></td><td><input data-k="${escapeHtml(s.key)}" data-f="neighborhood" value="${escapeHtml(m.neighborhood)}"></td><td><input data-k="${escapeHtml(s.key)}" data-f="nucleus" value="${escapeHtml(m.nucleus)}"></td><td><input data-k="${escapeHtml(s.key)}" data-f="siteType" value="${escapeHtml(m.siteType)}"></td><td>${escapeHtml(m.source||'Factura')}</td></tr>`;}).join('');}
function update(){refreshOptions();render();}
document.addEventListener('DOMContentLoaded',()=>{if(!records.length){$('filterSummary').textContent='No se encontró la base consolidada de las facturas.';return;}update();let inputTimer=0;document.querySelectorAll('#globalSiteSearch,#zoneFilter,#territoryTypeFilter,#communeFilter,#neighborhoodFilter,#nucleusFilter,#siteTypeFilter,#specificSiteFilter,#globalPeriodFilter,#globalServiceFilter,#priorityFilter').forEach(e=>e.addEventListener(e.tagName==='INPUT'?'input':'change',()=>{if(e.tagName==='INPUT'){clearTimeout(inputTimer);inputTimer=setTimeout(()=>requestAnimationFrame(update),120);}else requestAnimationFrame(update);}));$('clearSiteFiltersBtn')?.addEventListener('click',()=>{document.querySelectorAll('#globalSiteSearch,#zoneFilter,#territoryTypeFilter,#communeFilter,#neighborhoodFilter,#nucleusFilter,#siteTypeFilter,#specificSiteFilter,#globalPeriodFilter,#globalServiceFilter,#priorityFilter').forEach(e=>e.value='');update();});$('toggleClassificationBtn')?.addEventListener('click',()=>{const p=$('classificationPanel');p.hidden=!p.hidden;$('toggleClassificationBtn').textContent=p.hidden?'Revisar clasificación':'Cerrar clasificación';if(!p.hidden)renderClassification();});$('classificationBody')?.addEventListener('change',e=>{const k=e.target.dataset.k,f=e.target.dataset.f;if(!k||!f)return;manual[k]={...empty,...(SYNC[k]||{}),...(manual[k]||{}),[f]:e.target.value||'Sin clasificar',source:'Revisión manual',confidence:'Confirmada'};try{localStorage.setItem(META_KEY,JSON.stringify(manual));}catch{}update();});});
})();
