(() => {
'use strict';
const $ = id => document.getElementById(id);
const norm = v => String(v ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const fmt = v => new Intl.NumberFormat('es-CO',{maximumFractionDigits:2}).format(Number(v)||0);
const keyOf = (site,address='') => `${norm(site)}|${norm(address)}`;
const BASE = Array.isArray(window.SIMECO_REGISTROS) ? window.SIMECO_REGISTROS : [];
const SYNC = window.SIMECO_TERRITORIAL_SYNC || {};
const META_KEY='simeco2_clasificacion_sedes_energia_v3';
let manual={};
try{ manual=JSON.parse(localStorage.getItem(META_KEY)||'{}')||{}; }catch{ manual={}; }
const empty={zone:'Sin clasificar',territoryType:'Sin clasificar',commune:'Sin clasificar',neighborhood:'Sin clasificar',nucleus:'Sin clasificar',siteType:'Sin clasificar',source:'Factura',confidence:'Pendiente'};
const records=BASE.filter(r=>r&&r.site&&r.period).map(r=>({...r,energyKwh:Number(r.energyKwh)||0,co2kg:Number(r.co2kg)||((Number(r.energyKwh)||0)*0.126),address:r.address||''}));
const siteMap=new Map();
for(const r of records){const k=keyOf(r.site,r.address);if(!siteMap.has(k))siteMap.set(k,{key:k,site:r.site,address:r.address,records:[]});siteMap.get(k).records.push(r);}
function meta(k){return {...empty,...(SYNC[k]||{}),...(manual[k]||{})};}
function priority(total,months){const avg=months?total/months:0;return avg>=5000?'high':avg>=2000?'medium':'low';}
function filters(){return {q:norm($('globalSiteSearch')?.value),zone:$('zoneFilter')?.value||'',territoryType:$('territoryTypeFilter')?.value||'',commune:$('communeFilter')?.value||'',neighborhood:$('neighborhoodFilter')?.value||'',nucleus:$('nucleusFilter')?.value||'',siteType:$('siteTypeFilter')?.value||'',siteKey:$('specificSiteFilter')?.value||'',period:$('globalPeriodFilter')?.value||'',service:$('globalServiceFilter')?.value||'',priority:$('priorityFilter')?.value||''};}
function siteRows(){return [...siteMap.values()].map(s=>{const m=meta(s.key);const recs=s.records;const energy=recs.reduce((a,r)=>a+r.energyKwh,0);const periods=new Set(recs.map(r=>r.period)).size;return {...s,meta:m,energy,periods,priority:priority(energy,periods)};});}
function matchesSite(s,f,skip=''){
 const m=s.meta; const hay=norm([s.site,s.address,m.zone,m.territoryType,m.commune,m.neighborhood,m.nucleus,m.siteType].join(' '));
 if(skip!=='q'&&f.q&&!hay.includes(f.q))return false;
 for(const [field,val] of [['zone',f.zone],['territoryType',f.territoryType],['commune',f.commune],['neighborhood',f.neighborhood],['nucleus',f.nucleus],['siteType',f.siteType]]) if(skip!==field&&val&&norm(m[field])!==norm(val))return false;
 if(skip!=='siteKey'&&f.siteKey&&s.key!==f.siteKey)return false;
 if(skip!=='priority'&&f.priority&&s.priority!==f.priority)return false;
 return true;
}
function filteredRecords(){const f=filters();const allowed=new Set(siteRows().filter(s=>matchesSite(s,f)).map(s=>s.key));return records.filter(r=>{if(!allowed.has(keyOf(r.site,r.address)))return false;if(f.period&&r.period!==f.period)return false;if(f.service==='energia'&&!r.energyKwh)return false;if(f.service==='agua'&&!Number(r.waterM3))return false;if(f.service==='alcantarillado'&&!Number(r.alcM3))return false;if(f.service==='gas'&&!Number(r.gasM3))return false;if(f.service==='aseo'&&!(Number(r.wasteTon)||Number(r.wasteValue)))return false;return true;});}
function aggregate(recs){const map=new Map();for(const r of recs){const k=keyOf(r.site,r.address);if(!map.has(k))map.set(k,{key:k,site:r.site,address:r.address,energy:0,co2:0,periods:new Set()});const x=map.get(k);x.energy+=r.energyKwh;x.co2+=r.co2kg;x.periods.add(r.period);}return [...map.values()].map(x=>({...x,periodCount:x.periods.size,meta:meta(x.key)})).sort((a,b)=>b.energy-a.energy);}
function values(rows,field){return [...new Set(rows.map(x=>x.meta[field]||'Sin clasificar'))].sort((a,b)=>a.localeCompare(b,'es',{numeric:true}));}
function fill(id,vals,first,current){const e=$(id);if(!e)return;e.innerHTML=`<option value="">${first}</option>`+vals.map(v=>`<option>${escapeHtml(v)}</option>`).join('');const o=[...e.options].find(o=>norm(o.value)===norm(current));if(o)e.value=o.value;}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function refreshOptions(){const f=filters(),rows=siteRows();for(const [id,field,first] of [['zoneFilter','zone','Todas'],['territoryTypeFilter','territoryType','Todos'],['communeFilter','commune','Todas'],['neighborhoodFilter','neighborhood','Todos'],['nucleusFilter','nucleus','Todos'],['siteTypeFilter','siteType','Todos']])fill(id,values(rows.filter(s=>matchesSite(s,f,field)),field),first,f[field]);
 const matching=rows.filter(s=>matchesSite(s,f,'siteKey')).sort((a,b)=>a.site.localeCompare(b.site,'es'));const ss=$('specificSiteFilter');if(ss){ss.innerHTML='<option value="">Todas</option>'+matching.map(s=>`<option value="${escapeHtml(s.key)}">${escapeHtml(s.site)}</option>`).join('');if(matching.some(s=>s.key===f.siteKey))ss.value=f.siteKey;}
 fill('globalPeriodFilter',[...new Set(records.map(r=>r.period))].sort(),'Todos',f.period);
 const dl=$('siteSearchSuggestions');if(dl)dl.innerHTML=matching.slice(0,300).map(s=>`<option value="${escapeHtml(s.site)}"></option>`).join('');
}
function render(){const recs=filteredRecords();const rows=aggregate(recs);const energy=rows.reduce((a,x)=>a+x.energy,0),co2=rows.reduce((a,x)=>a+x.co2,0),periods=new Set(recs.map(r=>r.period)).size;
 $('territorialSitesCount').textContent=fmt(rows.length);$('territorialPeriodsCount').textContent=fmt(periods);$('territorialEnergyTotal').textContent=fmt(energy)+' kWh';$('territorialCo2Total').textContent=fmt(co2/1000)+' t CO₂e';
 $('territorialResultsBody').innerHTML=rows.slice(0,500).map((r,i)=>`<tr><td>${i+1}</td><td><strong>${escapeHtml(r.site)}</strong><small class="site-meta-line">${escapeHtml(r.address||'Sin dirección')}</small></td><td>${escapeHtml(r.meta.zone)}</td><td>${escapeHtml(r.meta.commune)}</td><td>${escapeHtml(r.meta.nucleus)}</td><td>${fmt(r.periodCount)}</td><td><strong>${fmt(r.energy)} kWh</strong></td><td>${fmt(r.co2/1000)} t</td></tr>`).join('')||'<tr><td colspan="8">No hay datos para los filtros seleccionados.</td></tr>';
 const f=filters();const active=Object.entries(f).filter(([,v])=>v).map(([k])=>k);$('filterStatus').textContent=active.length?'Filtros activos: '+active.join(', ')+'.':'Filtros listos · mostrando todas las sedes con datos.';$('filterSummary').innerHTML=`Mostrando <strong>${fmt(rows.length)} sede(s)</strong> y <strong>${fmt(recs.length)} registro(s)</strong> obtenidos de las facturas de servicios públicos.`;draw(rows.slice(0,20));
}
function draw(rows){const c=$('siteChart');if(!c)return;const dpr=Math.min(devicePixelRatio||1,2),w=1500,rowH=42,h=Math.max(420,100+rows.length*rowH);c.width=w*dpr;c.height=h*dpr;c.style.width=w+'px';c.style.height=h+'px';const x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);x.font='700 18px system-ui';x.fillStyle='#153b34';x.fillText('Ranking de sedes por consumo eléctrico total',24,35);x.font='600 12px system-ui';x.fillStyle='#607a74';x.fillText('Datos provenientes de las facturas de servicios públicos',24,55);const max=Math.max(...rows.map(r=>r.energy),1);rows.forEach((r,i)=>{const y=85+i*rowH;x.fillStyle='#173d36';x.font='600 12px system-ui';x.fillText((r.site||'').slice(0,34),20,y+14);x.fillStyle='#e8f5f1';x.fillRect(300,y,650,20);x.fillStyle='#10ae88';x.fillRect(300,y,650*r.energy/max,20);x.fillStyle='#173d36';x.fillText(`${fmt(r.energy)} kWh · ${fmt(r.co2/1000)} t CO₂e`,970,y+14);});}
function renderClassification(){const body=$('classificationBody');if(!body)return;body.innerHTML=siteRows().map(s=>{const m=s.meta;return `<tr><td><strong>${escapeHtml(s.site)}</strong></td><td>${escapeHtml(s.address)}</td><td><input data-k="${escapeHtml(s.key)}" data-f="zone" value="${escapeHtml(m.zone)}"></td><td><input data-k="${escapeHtml(s.key)}" data-f="territoryType" value="${escapeHtml(m.territoryType)}"></td><td><input data-k="${escapeHtml(s.key)}" data-f="commune" value="${escapeHtml(m.commune)}"></td><td><input data-k="${escapeHtml(s.key)}" data-f="neighborhood" value="${escapeHtml(m.neighborhood)}"></td><td><input data-k="${escapeHtml(s.key)}" data-f="nucleus" value="${escapeHtml(m.nucleus)}"></td><td><input data-k="${escapeHtml(s.key)}" data-f="siteType" value="${escapeHtml(m.siteType)}"></td><td>${escapeHtml(m.source||'Factura')}</td></tr>`;}).join('');}
function update(){refreshOptions();render();}
document.addEventListener('DOMContentLoaded',()=>{if(!records.length){$('filterSummary').textContent='No se encontró la base consolidada de las facturas.';return;}update();document.querySelectorAll('#globalSiteSearch,#zoneFilter,#territoryTypeFilter,#communeFilter,#neighborhoodFilter,#nucleusFilter,#siteTypeFilter,#specificSiteFilter,#globalPeriodFilter,#globalServiceFilter,#priorityFilter').forEach(e=>e.addEventListener(e.tagName==='INPUT'?'input':'change',update));$('clearSiteFiltersBtn')?.addEventListener('click',()=>{document.querySelectorAll('#globalSiteSearch,#zoneFilter,#territoryTypeFilter,#communeFilter,#neighborhoodFilter,#nucleusFilter,#siteTypeFilter,#specificSiteFilter,#globalPeriodFilter,#globalServiceFilter,#priorityFilter').forEach(e=>e.value='');update();});$('toggleClassificationBtn')?.addEventListener('click',()=>{const p=$('classificationPanel');p.hidden=!p.hidden;$('toggleClassificationBtn').textContent=p.hidden?'Revisar clasificación':'Cerrar clasificación';if(!p.hidden)renderClassification();});$('classificationBody')?.addEventListener('change',e=>{const k=e.target.dataset.k,f=e.target.dataset.f;if(!k||!f)return;manual[k]={...empty,...(SYNC[k]||{}),...(manual[k]||{}),[f]:e.target.value||'Sin clasificar',source:'Revisión manual',confidence:'Confirmada'};try{localStorage.setItem(META_KEY,JSON.stringify(manual));}catch{}update();});});
})();
