const fs=require('fs'),vm=require('vm');
function ok(v,m){if(!v)throw new Error(m)}
const errors=[],listeners={};
class CL{constructor(){this.s=new Set()}add(...x){x.forEach(v=>this.s.add(v))}remove(...x){x.forEach(v=>this.s.delete(v))}toggle(v,on){if(on===undefined){if(this.s.has(v)){this.s.delete(v);return false}this.s.add(v);return true}on?this.s.add(v):this.s.delete(v);return on}contains(v){return this.s.has(v)}}
const ctx={clearRect(){},fillRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},fill(){},arc(){},arcTo(){},closePath(){},save(){},restore(){},setLineDash(){},fillText(){},measureText(t){return{width:String(t).length*7}},createLinearGradient(){return{addColorStop(){}}},roundRect(){},strokeRect(){},translate(){},rotate(){},font:'',fillStyle:'',strokeStyle:'',lineWidth:1,textAlign:'left'};
class E{constructor(id=''){this.id=id;this.value='';this.innerHTML='';this.textContent='';this.hidden=false;this.disabled=false;this.style={setProperty(){}};this.dataset={};this.classList=new CL();this.options=[];this.children=[];this.width=1200;this.height=520;this.parentElement={clientWidth:1250}} addEventListener(){} setAttribute(k,v){this[k]=String(v)} getAttribute(k){return this[k]??null} removeAttribute(k){delete this[k]} appendChild(x){this.children.push(x);return x} remove(){} focus(){} select(){} click(){} scrollIntoView(){} querySelector(){return null} querySelectorAll(){return[]} closest(){return null} getContext(){return ctx} getBoundingClientRect(){return{left:0,top:0,width:this.width,height:this.height,right:this.width,bottom:this.height}}}
const els=new Map(),get=id=>{if(!els.has(id))els.set(id,new E(id));return els.get(id)};
const document={getElementById:get,querySelector(){return null},querySelectorAll(){return[]},createElement(t){return new E(t)},body:new E('body'),head:new E('head'),documentElement:new E('html'),styleSheets:[],addEventListener(n,f){listeners[n]=f}};
const c={window:{},document,localStorage:{getItem(){return null},setItem(){},removeItem(){}},console:{log(){},warn(){},error(...a){errors.push(a.map(String).join(' '))}},setTimeout(fn){try{fn()}catch(e){errors.push(e.stack)}return 1},clearTimeout(){},setInterval(){return 1},clearInterval(){},requestAnimationFrame(fn){try{fn()}catch(e){errors.push(e.stack)}return 1},performance,URL,Blob,TextEncoder,TextDecoder,Intl,navigator:{},location:{hash:'',href:'',origin:'file://',search:'',protocol:'file:',host:'',hostname:'',pathname:'/index.html'},history:{replaceState(){}},addEventListener(n,f){listeners[n]=f},alert(){},confirm(){return true},fetch:async()=>({ok:false,status:404,json:async()=>({}),text:async()=>''}),FileReader:class{},DOMParser:class{},Image:class{}};
c.window=c;c.globalThis=c;vm.createContext(c);
for(const f of ['data/registros.electricidad.min.js','data/resumenes.electricidad.min.js','data/sincronizacion-territorial.js','data/excepciones-servicios.js','app.js']) vm.runInContext(fs.readFileSync(f,'utf8'),c,{filename:f});
(async()=>{const r=listeners.DOMContentLoaded?.();if(r?.then)await r;ok(vm.runInContext('state.records.length',c)===9147,'No se hidrataron 9.147 registros');ok(errors.length===0,'Errores de runtime: '+errors.join(' | '));for(const fn of ['renderAll','renderDashboard','renderDataQuality','renderTable','renderRanking','refreshHistoryModule','generateManagementPlan'])ok(vm.runInContext(`typeof ${fn}`,c)==='function',`Falta ${fn}`);console.log(JSON.stringify({ok:true,records:9147,runtimeErrors:0,renderers:7},null,2));})().catch(e=>{console.error(e);process.exit(1)});
